name: Deploy website

on:
  workflow_dispatch:
#  push:
#    branches: [ $default-branch ]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
    - name: Build website
      run: |
        npm install
        npm run build
        
    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1
      with:
        source-path: build
        sas-url: ${{ secrets.DEPLOY_SAS_URL }} # https://github.com/marketplace/actions/deploy-to-azure-storage#how-to-get-a-sas-url-and-save-it
